package JPanels;

import java.awt.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.*;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;

public class g {


    public g() {
        initComponents();
        initComponents();
    }

    private void initComponents() {
        // JFormDesigner - Component initialization - DO NOT MODIFY  //GEN-BEGIN:initComponents  @formatter:off
        // Generated using JFormDesigner Evaluation license - unknown
        panel1 = new JPanel();
        textArea1 = new JTextArea();

        //======== panel1 ========
        {
            panel1.setBorder (new CompoundBorder( new TitledBorder (new EmptyBorder( 0, 0, 0, 0) , "JF\u006frmD\u0065sig\u006eer \u0045val\u0075ati\u006fn", TitledBorder. CENTER, TitledBorder. BOTTOM, new Font ("Dia\u006cog"
            ,Font .BOLD ,12 ), Color. red) ,panel1. getBorder
            ( )) ); panel1. addPropertyChangeListener (new PropertyChangeListener( ){ @Override public void propertyChange (PropertyChangeEvent e) {if ("\u0062ord\u0065r" .equals (e .getPropertyName () )) throw new RuntimeException
            ( ); }} );
            panel1.setLayout(new BorderLayout());
            panel1.add(textArea1, BorderLayout.WEST);
        }
        // JFormDesigner - End of component initialization  //GEN-END:initComponents  @formatter:on
    }

    // JFormDesigner - Variables declaration - DO NOT MODIFY  //GEN-BEGIN:variables  @formatter:off
    // Generated using JFormDesigner Evaluation license - unknown
    private JPanel panel1;
    private JTextArea textArea1; {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
$$$setupUI$$$();
} /** Method generated by IntelliJ IDEA GUI Designer
 * >>> IMPORTANT!! <<<
 * DO NOT edit this method OR call it in your code!
 * @noinspection ALL
 */
private void $$$setupUI$$$()
{
panel1=new JPanel();
panel1.setLayout(new BorderLayout(0,0));
panel1.setBackground(new Color(-16502775));
textArea1=new JTextArea();
textArea1.setBackground(new Color(-15519708));
panel1.add(textArea1,BorderLayout.WEST);
} /** @noinspection ALL */ public JComponent $$$getRootComponent$$$() { return panel1; }
    // JFormDesigner - End of variables declaration  //GEN-END:variables  @formatter:on
}
